# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

networks:
  dev_env_network:
    driver: bridge

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dev_env_network
  publisherservice:
    image: publisherservice
    depends_on:
      - redis
    build:
      context: .
      dockerfile: PublisherService/Dockerfile
    ports:
      - "8000:5000"
    networks:
      - dev_env_network
  subscriberworker:
    image: subscriberworker
    depends_on:
      - redis
    build:
      context: .
      dockerfile: SubscriberWorker/Dockerfile
    networks:
      - dev_env_network